# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    volumes:
      - /root/PostgreSQL/db-data:/var/lib/mysql/
      - /root/PostgreSQL/db-backup:/tmp/postgres/backup
